### ISSUE TITLE
Can't get this to work at all.

### ISSUE THREAD

**Issue by itsbrex** [uetchy/Sketch-StickyGrid#2]
I've downloaded, unzipped, and moved entire folder to sketch plugins folder, but when I try activating the plugin after selecting the vector drawing nothing happens. Thoughts?

**Comment by uetchy** [comment]
Confirmed. I'm working on branch 'sketch-3.3' to support new version of Sketch.app but I have no idea to fix them.
Debugging tool(Sketch-DevTools) is still unavailable in Sketch 3.3.
Do you have any idea?

**Comment by brianroach** [comment]
I don't, sorry. I'm pretty new to programming so right now this is over my head. Maybe place a bounty for a quick fix?

**Comment by uetchy** [comment]
Now start supporting Sketch 3.3+.
You can get latest releases from [there](https://github.com/uetchy/Sketch-StickyGrid/releases/tag/v2.0.0).
