### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by ryanmclaughlin** [uetchy/Sketch-StickyGrid#4]
I know Sketch has pixel rounding features, but it doesn't always work as expected and was hoping this plugin still worked. Am I using it incorrectly?

Apologies – difficult to tell from the gif, but it running the plugin doesn't do anything to the paths.

![sketch_snap](https://cloud.githubusercontent.com/assets/451112/13261272/33a9c0a0-da14-11e5-9b5e-085850d3867e.gif)

**Comment by uetchy** [comment]
Can you upload .sketch file in this gif video?
I need this file for debugging the plugin.

**Comment by ryanmclaughlin** [comment]
Sure. Here you are:
[StickyGrid_Repro.sketch.zip](https://github.com/uetchy/Sketch-StickyGrid/files/162536/StickyGrid_Repro.sketch.zip)

**Comment by ElegantSudo** [comment]
@uetchy this still doesn't work. I wish it did.

**Comment by ElegantSudo** [comment]
@uetchy can you please fix this? It'd make life so much easier.

**Comment by ElegantSudo** [comment]
@uetchy Upon running I get this error. It looks like [MSDocument](http://developer.sketchapp.com/reference/class/MSDocument/) doesn't have a grid method/function.

```
TypeError: null is not an object (evaluating 'doc.grid().gridSize')
line: 41
sourceURL: /Users/user/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Untitled.sketchplugin
column: 32
```

**Comment by uetchy** [comment]
@ElegantSudo Turned out that the error occurs only if we have artboards on a document.
I have worked on this issue, but I have no idea to fix them.
I'm wondering If you can help me out for this problem.

**Comment by ElegantSudo** [comment]
@uetchy We can get the artboard with `context.document.currentPage().currentArtboard()`, however attempting to get the artboard's grid with the `grid()` method doesn't work and returns null.

**Comment by ElegantSudo** [comment]
@bohemiancoding @bomberstudios any suggestions on this? ^^^ How can we use the `grid()` method on an artboard?

**Comment by bomberstudios** [comment]
`artboard.grid()` returns `null` if the grid has never been set for that particular artboard. In that case, you can just set the grid to the default using `MSDefaultGrid.defaultGrid()` by doing `context.document.currentPage().currentArtboard().grid = MSDefaultGrid.defaultGrid()`

Hope it helps!

**Comment by ElegantSudo** [comment]
Great! Now that that's fixed, we're getting an error that says `shapeLayer.adjustFrameAfterEdit is not a function.`

I've included some comments below of our updated script, where we're getting the errors, and what's changed. So far, this is what we have:

``` js
function computePosition(pos, intval) {
  return Math.round(pos / intval) * intval;
}

function adjustPointsTo(shapeLayer, gridInterval) {
  var path = shapeLayer.path();
  var pointsCount = path.numberOfPoints();
  var artboardFrame = shapeLayer.frameInArtboard();

  for (var j=0; j < pointsCount; j++) {
    var point = path.pointAtIndex(j);

    var absolutePoint = shapeLayer.absolutePoint(point.point());

    var relX = computePosition(
      artboardFrame.origin.x + absolutePoint.x,
      gridInterval) - (artboardFrame.origin.x + absolutePoint.x
    );

    var relY = computePosition(
      artboardFrame.origin.y + absolutePoint.y,
      gridInterval) - (artboardFrame.origin.y + absolutePoint.y);

    var cgPoint = shapeLayer.relativePoint(
      CGPointMake(
        absolutePoint.x + relX,
        absolutePoint.y + relY
      ));

    point.movePointTo(cgPoint);
  }

  shapeLayer.adjustFrameAfterEdit(); // <----- NOTE: Here's the error
}

function snapToGrid(context) {
  var app = [NSApplication sharedApplication];
  var selection = context.selection;
  var gridInterval = MSDefaultGrid.defaultGrid().gridSize(); // <----- NOTE: Here's what we've changed

  for (var i=0; i < [selection count]; i++) {
    var object = [selection objectAtIndex: i];

    if ([object isKindOfClass:[MSShapePathLayer class]]) {
      // MSShapeGroup
      adjustPointsTo(object, gridInterval);
    } else if ([object isMemberOfClass:[MSLayerGroup class]]) {
      // MSLayerGroup
      for (var l=0; l < [[object layers] count]; l++) {
        var shapeLayerGroup = [[object layers] objectAtIndex:l];

        for (var l2=0; l2 < [[shapeLayerGroup layers] count]; l2++)
          adjustPointsTo([[shapeLayerGroup layers] objectAtIndex:l2], gridInterval);
      }
    } else {
      // MSShapePathLayer
      for (var l=0; l < [[object layers] count]; l++)
        adjustPointsTo([[object layers] objectAtIndex:l], gridInterval);
    }
  }
}

snapToGrid(context);
```

**Comment by bomberstudios** [comment]
Try `adjustFrameAfterEditIntegral(false)`

**Comment by ElegantSudo** [comment]
@bomberstudios @uetchy well, we've got it running with no errors now - it just doesn't work.

![snap test artboard](https://cloud.githubusercontent.com/assets/19272022/15800112/2c06b882-2a3f-11e6-946c-3f330f5db73b.gif)

**Comment by uetchy** [comment]
@ElegantSudo I finally figured it out!
The grid in your screenshot is not Grid but Pixel Grid.
And this plugin is assumed to use with Grid (`^G` to show).

**Comment by uetchy** [comment]
OK. I added new command: `Snap to Pixel Grid`. See #6 for ongoing PR.

**Comment by uetchy** [comment]
[v3.0.0](https://github.com/uetchy/Sketch-StickyGrid/releases/tag/v3.0.0) is out.

**Comment by uetchy** [comment]
@ElegantSudo Is everything OK?

**Comment by ElegantSudo** [comment]
@uetchy it works beautifully. I've been using it in my recent Sketch designs for clients. It's main use is when importing other vector paths or converting text to shapes for modification. When you convert text to shapes for modification their paths don't snap to the pixels and that stinks because every designer wants pixel-perfect design.

Amazing job @uetchy, @bomberstudios should look to implement this into Sketch officially.

**Comment by ElegantSudo** [comment]
@bomberstudios when you select a shape, a button similar to this one should be displayed that says "Snap to Pixel Grid":

<img width="214" alt="screen shot 2016-06-12 at 8 34 35 pm" src="https://cloud.githubusercontent.com/assets/19272022/15994847/5222ad56-30dd-11e6-99c8-e90861977d55.png">

Again, amazing job @uetchy and @bomberstudios. I'll be converting my entire company to Sketch moving forward. It's amazing how useful a simple feature can be.

**Comment by bomberstudios** [comment]
FTR, "Snap to Pixel Grid" is already a native feature in Sketch (see Layer › Round to Pixel).

We'll see what we can do for the other feature : )

**Comment by ElegantSudo** [comment]
We should make it so that round to pixel also accounts for curvatures, not just points on a path.
